### ISSUE TITLE
前端备忘录

### ISSUE THREAD

**Issue by julytian** [julytian/issues-blog#1]
在 CSS 中 `pointer-events: none` 可以使得鼠标穿透该层，点击到下方元素。

伪元素中使用 `content: attr(data-*)` 可插入自定义属性中的内容。

单行文字长度自适应，超出长度显示省略号：

``` css
.class {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}
```
