### ISSUE TITLE
微信h5模板工具

### ISSUE THREAD

**Issue by julytian** [julytian/issues-blog#20]
## 快速制作微信h5

[京东的ELF](https://elf.aotu.io/)

[微信团队的 pageslider](https://github.com/weixin/PageSlider)

## loading炫酷css
```html
<div class="loading">
        <div class="inner"> <i class="before"></i> <i class="after"></i> </div>
        <div class="text">
            <span class="pace-progress"></span> <br>加载中...
        </div>
    </div>
```
```css

.loading {
    position: absolute;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    z-index: 9999;
    background-color: #363535
}

.loading .inner {
    display: block;
    position: absolute;
    left: 50%;
    top: 50%;
    width: 5.33333rem;
    height: 5.33333rem;
    margin: -2.66667rem 0 0 -2.66667rem;
    border-radius: 50%;
    border: .08rem solid transparent;
    border-top-color: #3498db;
    -webkit-animation: spin 2s linear infinite;
    animation: spin 2s linear infinite
}

.loading .inner .before {
    position: absolute;
    top: .13333rem;
    left: .13333rem;
    right: .13333rem;
    bottom: .13333rem;
    border-radius: 50%;
    border: .08rem solid transparent;
    border-top-color: #e74c3c;
    -webkit-animation: spin 3s linear infinite;
    animation: spin 3s linear infinite
}

.loading .inner .after {
    position: absolute;
    top: .4rem;
    left: .4rem;
    right: .4rem;
    bottom: .4rem;
    border-radius: 50%;
    border: .08rem solid transparent;
    border-top-color: #f9c922;
    -webkit-animation: spin 1.5s linear infinite;
    animation: spin 1.5s linear infinite
}

.loading .text {
    width: 3.66667rem;
    position: absolute;
    left: 48%;
    top: 48%;
    margin: -.8rem 0 0 -1.33333rem;
    line-height: 1.6rem;
    font-size: .8rem;
    text-align: center;
    color: #eadcdb
}

@-webkit-keyframes spin {
    0% {
        -webkit-transform: rotate(0deg);
        transform: rotate(0deg)
    }
    to {
        -webkit-transform: rotate(1turn);
        transform: rotate(1turn)
    }
}

@keyframes spin {
    0% {
        -webkit-transform: rotate(0deg);
        transform: rotate(0deg)
    }
    to {
        -webkit-transform: rotate(1turn);
        transform: rotate(1turn)
    }
}
```
