### ISSUE TITLE
移动端知识汇聚

### ISSUE THREAD

**Issue by julytian** [julytian/issues-blog#3]
## 解决 position:fixed

移动端一般会把头部，尾部固定不滚动，传统用法：`position:fixed`。但是在一些低版本浏览器，例如：QQ浏览器就不支持这个写法。解决方法，使用 `position:absolute`。

记住滚动条是html身上的，所以需要隐藏滚动条。

``` css
html {
width:100%;
height: 100%;
overflow: hidden;
}
body{
width:100%;
height: 100%;
overflow: auto;
}
```
