### ISSUE TITLE
移动端页面开发资源总结

### ISSUE THREAD

**Issue by julytian** [julytian/issues-blog#6]
## css reset

``` css
@charset "utf-8";
/* reset */
html{
    -webkit-text-size-adjust:none;
    -webkit-user-select:none;
    -webkit-touch-callout: none
    font-family: Helvetica;
}
body{font-size:12px;}
body,h1,h2,h3,h4,h5,h6,p,dl,dd,ul,ol,pre,form,input,textarea,th,td,select{margin:0; padding:0; font-weight: normal;text-indent: 0;}
a,button,input,textarea,select{ background: none; -webkit-tap-highlight-color:rgba(255,0,0,0); outline:none; -webkit-appearance:none;}
em{font-style:normal}
li{list-style:none}
a{text-decoration:none;}
img{border:none; vertical-align:top;}
table{border-collapse:collapse;}
textarea{ resize:none; overflow:auto;}
/* end reset */
```
## 公用CSS style

``` css
/* public */

/* 清除浮动 */
.clear { zoom:1; }
.clear:after { content:''; display:block; clear:both; }

/* 定义盒模型为怪异和模型（宽高不受边框影响） */
.boxSiz{
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    -ms-box-sizing: border-box;
    -o-box-sizing: border-box;
    box-sizing: border-box;
}

/* 强制换行 */
.toWrap{
    word-break: break-all;       /* 只对英文起作用，以字母作为换行依据。 */
    word-wrap: break-word;      /* 只对英文起作用，以单词作为换行依据。*/
    white-space: pre-wrap;     /* 只对中文起作用，强制换行。*/
}

/* 禁止换行 */
.noWrap{
    white-space:nowrap;
}

/* 禁止换行,超出省略号 */
.noWrapEllipsis{
     white-space:nowrap; overflow:hidden; text-overflow:ellipsis;
}

/* 文字两端对齐 */
.text-justify{
    text-align:justify; 
    text-justify:inter-ideograph;
}

/* 定义盒模型为 flex布局兼容写法并让内容水平垂直居中 */
.flex-center{
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -o-box;
    display: box;
    -webkit-box-pack: center;
      -moz-box-pack: center;
      -ms-flex-pack: center;
      -o-box-pack: center;
      box-pack: center;
    -webkit-box-align: center;
    -moz-box-align: center;
    -ms-flex-align: center;
    -o-box-align: center;
    box-align: center;
}
/* public end */
```
## viewport模板

``` html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no" name="viewport">
<meta content="yes" name="apple-mobile-web-app-capable">
<meta content="black" name="apple-mobile-web-app-status-bar-style">
<meta content="telephone=no" name="format-detection">
<meta content="email=no" name="format-detection">
<title>title</title>
<link rel="stylesheet" href="index.css">
</head>

<body>
    content...
</body>

</html>
```
## CSS样式技巧

**1. 禁止ios和android用户选中文字**

``` css
.css{-webkit-user-select:none}
```

**2、禁止ios长按时触发系统的菜单，禁止ios&android长按时下载图片**

``` css
.css{-webkit-touch-callout: none}
```

**3、webkit去除表单元素的默认样式**

``` css
.css{-webkit-appearance:none;}
```

**4、修改webkit表单输入框placeholder的样式**

``` css
input::-webkit-input-placeholder{color:#AAAAAA;}
input:focus::-webkit-input-placeholder{color:#EEEEEE;}
```

**5、去除android a/button/input标签被点击时产生的边框 & 去除ios a标签被点击时产生的半透明灰色背景**

``` css
a,button,input{-webkit-tap-highlight-color:rgba(255,0,0,0);}
```

**6、ios使用-webkit-text-size-adjust禁止调整字体大小**

``` css
body{-webkit-text-size-adjust: 100%!important;}
```

**7、android 上去掉语音输入按钮**

``` css
input::-webkit-input-speech-button {display: none}
```

**8、移动端定义字体，移动端没有微软雅黑字体**

``` css
/* 移动端定义字体的代码 */
body{font-family:Helvetica;}
```

**9、禁用Webkit内核浏览器的文字大小调整功能。**

``` css
-webkit-text-size-adjust: none;
```
## 其他技巧

**1、手机拍照和上传图片**

``` html
<!-- 选择照片 -->
<input type=file accept="image/*">
<!-- 选择视频 -->
<input type=file accept="video/*">
```

**2、取消input在ios下，输入的时候英文首字母的默认大写**

``` html
<input autocapitalize="off" autocorrect="off" />
```

**3、打电话和发短信**

``` html
<a href="tel:0755-10086">打电话给:0755-10086</a>
<a href="sms:10086">发短信给: 10086</a>
```

[来源](http://hcysun.me/2015/09/25/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E9%A1%B5%E9%9D%A2%E5%BC%80%E5%8F%91%E8%B5%84%E6%BA%90%E6%80%BB%E7%BB%93/)
### [移动端300ms点击延迟和点击穿透问题](http://www.jianshu.com/p/6e2b68a93c88)

[FastClick](https://github.com/ftlabs/fastclick) 是 FT Labs 专门为解决移动端浏览器 300 毫秒点击延迟问题所开发的一个轻量级的库
