### ISSUE TITLE
sass mixin集合

### ISSUE THREAD

**Issue by julytian** [julytian/issues-blog#9]
**px转rem**

``` css
@function px2em($px, $base-font-size: 20px) {
  @if (unitless($px)) {
    @warn "Assuming #{$px} to be in pixels, attempting to convert it into pixels for you";
    @return px2em($px + 0px); // That may fail.
  } @else if (unit($px) == rem) {
    @return $px;
  }
  @return ($px / $base-font-size) * 1rem;
}
```

**opacity**

``` css
@mixin opacity($opacity:50) {
  opacity: $opacity / 100;
  filter: alpha(opacity=$opacity);
}
```

**box-shadow**

``` css
@mixin box-shadow($shadow...) {
  -webkit-box-shadow:$shadow;
  box-shadow:$shadow;
}
```

**text省略符**

``` css
@mixin text-overflow() {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```
